@component('mail::message')

Dear {{$data['user_name']}},

We hope this email finds you well.

We wanted to inform you that a transfer of funds has been initiated from your account. To ensure the security of your account and to complete the transfer process, we kindly request your confirmation.

If you have initiated this transfer, please proceed to verify the transaction by providing the OTP {{$data['randomNumber']}} generated by our system.


@endcomponent
